/* ──────────────────────────────────────────────
 *  Dummy Data – Alwan Marketplace
 *  Replace this placeholder data with real content
 *  when connecting to a backend / CMS.
 * ────────────────────────────────────────────── */

/* ─── Categories ─── */
export const categories = [
  { id: 1, name: "Embroidery", icon: "🧵", count: 245 },
  { id: 2, name: "Mehndi", icon: "✋", count: 189 },
  { id: 3, name: "Crochet", icon: "🧶", count: 134 },
  { id: 4, name: "Stitching", icon: "👗", count: 312 },
  { id: 5, name: "Fashion Design", icon: "✂️", count: 98 },
  { id: 6, name: "Tutoring", icon: "📚", count: 156 },
  { id: 7, name: "Handmade Crafts", icon: "🎨", count: 278 },
  { id: 8, name: "Jewelry Making", icon: "💍", count: 87 },
];

/* ─── Featured Creators ─── */
export const featuredCreators = [
  {
    id: 1,
    name: "Ayesha Khan",
    skill: "Embroidery Artist",
    city: "Lahore",
    rating: 4.9,
    reviews: 128,
    image: "/placeholder-creator-1.jpg",
    bio: "Specializing in traditional Mughal-inspired embroidery with over 10 years of experience. Every stitch tells a story of heritage and love.",
    skills: ["Hand Embroidery", "Machine Embroidery", "Zardozi", "Thread Work"],
    portfolio: ["/placeholder-portfolio-1.jpg", "/placeholder-portfolio-2.jpg", "/placeholder-portfolio-3.jpg", "/placeholder-portfolio-4.jpg"],
  },
  {
    id: 2,
    name: "Fatima Malik",
    skill: "Mehndi Designer",
    city: "Karachi",
    rating: 4.8,
    reviews: 95,
    image: "/placeholder-creator-2.jpg",
    bio: "Award-winning mehndi artist known for intricate bridal designs blending Arabic and Pakistani traditions.",
    skills: ["Bridal Mehndi", "Arabic Designs", "Modern Patterns", "Finger Mehndi"],
    portfolio: ["/placeholder-portfolio-5.jpg", "/placeholder-portfolio-6.jpg", "/placeholder-portfolio-7.jpg", "/placeholder-portfolio-8.jpg"],
  },
  {
    id: 3,
    name: "Sana Ahmed",
    skill: "Crochet Expert",
    city: "Islamabad",
    rating: 4.7,
    reviews: 76,
    image: "/placeholder-creator-3.jpg",
    bio: "Creating beautiful handmade crochet pieces from home decor to wearable fashion. Every piece is unique and made with love.",
    skills: ["Amigurumi", "Blankets", "Wearables", "Home Decor"],
    portfolio: ["/placeholder-portfolio-9.jpg", "/placeholder-portfolio-10.jpg", "/placeholder-portfolio-11.jpg", "/placeholder-portfolio-12.jpg"],
  },
  {
    id: 4,
    name: "Zainab Ali",
    skill: "Fashion Designer",
    city: "Faisalabad",
    rating: 4.9,
    reviews: 142,
    image: "/placeholder-creator-4.jpg",
    bio: "Contemporary fashion meets traditional Pakistani craftsmanship. Designing bespoke outfits for the modern woman.",
    skills: ["Bridal Wear", "Casual Wear", "Formal Design", "Pattern Making"],
    portfolio: ["/placeholder-portfolio-13.jpg", "/placeholder-portfolio-14.jpg", "/placeholder-portfolio-15.jpg", "/placeholder-portfolio-16.jpg"],
  },
];

/* ─── Marketplace Products/Services ─── */
export const marketplaceItems = [
  {
    id: 1,
    title: "Custom Bridal Embroidery Set",
    creator: "Ayesha Khan",
    creatorId: 1,
    category: "Embroidery",
    price: 15000,
    rating: 4.9,
    reviews: 42,
    image: "/placeholder-product-1.jpg",
    description: "Handcrafted bridal embroidery with gold and silver threadwork.",
  },
  {
    id: 2,
    title: "Bridal Mehndi Package",
    creator: "Fatima Malik",
    creatorId: 2,
    category: "Mehndi",
    price: 8000,
    rating: 4.8,
    reviews: 56,
    image: "/placeholder-product-2.jpg",
    description: "Full bridal mehndi service including hands and feet with premium quality mehndi.",
  },
  {
    id: 3,
    title: "Handmade Crochet Blanket",
    creator: "Sana Ahmed",
    creatorId: 3,
    category: "Crochet",
    price: 5500,
    rating: 4.7,
    reviews: 31,
    image: "/placeholder-product-3.jpg",
    description: "Cozy handmade crochet blanket in custom colors and patterns.",
  },
  {
    id: 4,
    title: "Custom Formal Dress Design",
    creator: "Zainab Ali",
    creatorId: 4,
    category: "Fashion Design",
    price: 25000,
    rating: 4.9,
    reviews: 68,
    image: "/placeholder-product-4.jpg",
    description: "Bespoke formal dress designed and stitched to your measurements.",
  },
  {
    id: 5,
    title: "Traditional Phulkari Dupatta",
    creator: "Ayesha Khan",
    creatorId: 1,
    category: "Embroidery",
    price: 7500,
    rating: 4.8,
    reviews: 24,
    image: "/placeholder-product-5.jpg",
    description: "Authentic Phulkari embroidered dupatta with vibrant thread work.",
  },
  {
    id: 6,
    title: "Party Mehndi Design",
    creator: "Fatima Malik",
    creatorId: 2,
    category: "Mehndi",
    price: 3000,
    rating: 4.6,
    reviews: 38,
    image: "/placeholder-product-6.jpg",
    description: "Elegant party mehndi for both hands with modern patterns.",
  },
  {
    id: 7,
    title: "Crochet Amigurumi Collection",
    creator: "Sana Ahmed",
    creatorId: 3,
    category: "Crochet",
    price: 2500,
    rating: 4.9,
    reviews: 19,
    image: "/placeholder-product-7.jpg",
    description: "Adorable handmade crochet amigurumi toys perfect for gifts.",
  },
  {
    id: 8,
    title: "Summer Lawn Collection",
    creator: "Zainab Ali",
    creatorId: 4,
    category: "Fashion Design",
    price: 12000,
    rating: 4.7,
    reviews: 45,
    image: "/placeholder-product-8.jpg",
    description: "Custom-designed lawn outfit with unique prints and patterns.",
  },
  {
    id: 9,
    title: "Handmade Beaded Jewelry Set",
    creator: "Noor Fatima",
    creatorId: 5,
    category: "Handmade Crafts",
    price: 3500,
    rating: 4.8,
    reviews: 33,
    image: "/placeholder-product-9.jpg",
    description: "Beautiful handcrafted beaded necklace and earring set.",
  },
  {
    id: 10,
    title: "Math Tutoring (O-Level)",
    creator: "Hira Naz",
    creatorId: 6,
    category: "Tutoring",
    price: 5000,
    rating: 4.9,
    reviews: 52,
    image: "/placeholder-product-10.jpg",
    description: "Monthly online tutoring for O-Level math with personalized attention.",
  },
  {
    id: 11,
    title: "Custom Stitching Service",
    creator: "Rabia Saleem",
    creatorId: 7,
    category: "Stitching",
    price: 4000,
    rating: 4.6,
    reviews: 27,
    image: "/placeholder-product-11.jpg",
    description: "Professional stitching service for suits, kurtas, and more.",
  },
  {
    id: 12,
    title: "Decorative Wall Hanging",
    creator: "Sana Ahmed",
    creatorId: 3,
    category: "Handmade Crafts",
    price: 4500,
    rating: 4.7,
    reviews: 15,
    image: "/placeholder-product-12.jpg",
    description: "Handmade macramé wall hanging for home décor.",
  },
];

/* ─── Testimonials ─── */
export const testimonials = [
  {
    id: 1,
    name: "Mariam Bibi",
    role: "Creator – Embroidery",
    city: "Multan",
    content: "Alwan changed my life. I was doing embroidery at home for years, but nobody knew about my work. Now I have customers from all over Pakistan. My family is so proud of me.",
    rating: 5,
    image: "/placeholder-testimonial-1.jpg",
  },
  {
    id: 2,
    name: "Sara Qureshi",
    role: "Customer",
    city: "Karachi",
    content: "I found the most amazing mehndi artist for my sister's wedding through Alwan. The quality was incredible and the process was so smooth. This platform is a game changer!",
    rating: 5,
    image: "/placeholder-testimonial-2.jpg",
  },
  {
    id: 3,
    name: "Hina Parveen",
    role: "Creator – Crochet",
    city: "Lahore",
    content: "As a single mother, Alwan gave me the opportunity to earn from home while taking care of my children. I'm now financially independent and it feels incredible.",
    rating: 5,
    image: "/placeholder-testimonial-3.jpg",
  },
];

/* ─── How It Works Steps ─── */
export const howItWorksSteps = [
  {
    step: 1,
    title: "Create Your Profile",
    description: "Sign up and showcase your talent with a beautiful creator profile. Add your skills, portfolio, and pricing.",
    icon: "✨",
  },
  {
    step: 2,
    title: "Get Discovered",
    description: "Customers browse and find your services through our curated marketplace. No middlemen, direct connections.",
    icon: "🔍",
  },
  {
    step: 3,
    title: "Earn & Grow",
    description: "Receive payments directly, build your reputation with reviews, and grow your creative business.",
    icon: "💰",
  },
];

/* ─── Reviews (for creator profile page) ─── */
export const creatorReviews = [
  {
    id: 1,
    reviewer: "Amna Sheikh",
    rating: 5,
    date: "2026-01-15",
    comment: "Absolutely stunning work! The embroidery detail was beyond my expectations. Will definitely order again.",
  },
  {
    id: 2,
    reviewer: "Rabia Qasim",
    rating: 5,
    date: "2026-01-08",
    comment: "Professional, punctual, and incredibly talented. The bridal set was a masterpiece.",
  },
  {
    id: 3,
    reviewer: "Nida Hussain",
    rating: 4,
    date: "2025-12-20",
    comment: "Beautiful work and great communication throughout. Highly recommend to everyone.",
  },
  {
    id: 4,
    reviewer: "Kiran Abbas",
    rating: 5,
    date: "2025-12-10",
    comment: "The Phulkari dupatta I ordered was gorgeous. Perfect craftsmanship with attention to every detail.",
  },
];

/* ─── Cities for the Join form ─── */
export const pakistanCities = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Hyderabad",
  "Gujranwala",
  "Bahawalpur",
  "Sargodha",
  "Abbottabad",
  "Mardan",
  "Sukkur",
];

/* ─── Skill Categories for Join form ─── */
export const skillCategories = [
  "Embroidery",
  "Mehndi",
  "Crochet",
  "Stitching",
  "Fashion Design",
  "Tutoring",
  "Handmade Crafts",
  "Jewelry Making",
  "Calligraphy",
  "Baking & Cooking",
  "Other",
];
