-- Alwan: Messages table for contact form submissions
-- Run this once in Supabase SQL Editor

create table if not exists public.creator_messages (
  id bigint generated by default as identity primary key,
  creator_id integer not null,
  creator_name text not null,
  sender_name text not null,
  sender_email text not null,
  sender_phone text,
  sender_city text,
  message text not null,
  created_at timestamptz not null default now()
);

-- Helpful indexes
create index if not exists idx_creator_messages_creator_id on public.creator_messages(creator_id);
create index if not exists idx_creator_messages_created_at on public.creator_messages(created_at desc);
